# Generated by Django 3.0.2 on 2020-01-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
